# Generated by Django 3.2.7 on 2021-09-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offert", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="features",
        ),
    ]
