# Generated by Django 3.2.7 on 2021-09-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offert", "0002_remove_product_features"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="category",
        ),
        migrations.RemoveField(
            model_name="images",
            name="product",
        ),
        migrations.RemoveField(
            model_name="price",
            name="product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="added_by",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AlterUniqueTogether(
            name="productfeature",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="productfeature",
            name="feature",
        ),
        migrations.RemoveField(
            model_name="productfeature",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productrate",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productrate",
            name="user",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Feature",
        ),
        migrations.DeleteModel(
            name="Images",
        ),
        migrations.DeleteModel(
            name="Price",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductFeature",
        ),
        migrations.DeleteModel(
            name="ProductRate",
        ),
    ]
