# Generated by Django 3.2.7 on 2021-09-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offert", "0002_feature"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feature",
        ),
    ]
