# Generated by Django 3.2.7 on 2021-09-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offert", "0004_feature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="unit",
        ),
    ]
