# Generated by Django 3.2.7 on 2021-09-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "offert",
            "0004_category_feature_images_price_product_productfeature_productrate",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="features",
            field=models.ManyToManyField(
                related_name="features",
                through="offert.ProductFeature",
                to="offert.Feature",
            ),
        ),
    ]
