# Generated by Django 3.2.7 on 2021-09-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offert', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='category/default_photo.png', upload_to='category/'),
        ),
    ]
